import { useGameStore } from "../../data/stores/useGameStore";

export const useGameViewModel = () => {
  const {
    phase,
    player,
    mapNodes,
    currentNodeId,
    enemies,
    turnOrder,
    currentTurnIndex,
    battleLog,
    selectedCard,
    isTargeting,
    levelUpData,
    evolutionData,
    restHealAmount,
    initializeRun,
    proceedToNode,
    selectNode,
    selectCard,
    selectTarget,
    cancelTarget,
    endTurn,
    executeEnemyAction,
    acknowledgeLevelUp,
    acknowledgeEvolution,
    acknowledgeRest,
    resetRun,
  } = useGameStore();

  return {
    phase,
    player,
    mapNodes,
    currentNodeId,
    enemies,
    turnOrder,
    currentTurnIndex,
    battleLog,
    selectedCard,
    isTargeting,
    levelUpData,
    evolutionData,
    restHealAmount,
    initializeRun,
    proceedToNode,
    selectNode,
    selectCard,
    selectTarget,
    cancelTarget,
    endTurn,
    executeEnemyAction,
    acknowledgeLevelUp,
    acknowledgeEvolution,
    acknowledgeRest,
    resetRun,
  };
};
